#!/usr/bin/env python3
"""Regenerate the Reconclave identity headers from the single source of truth.

`common/identity/identity.json` is authoritative. This script derives the
C++ header (`common/identity/include/reconclave/identity.h`) and the web
stylesheet (`common/identity/identity.css`) from it so the palette, brand
strings, and device roster cannot silently drift across the fleet again.

Run from the repository root:

    python3 tools/generate_identity.py           # regenerate
    python3 tools/generate_identity.py --check    # fail if out of date (for CI)

The `--check` mode regenerates in memory and compares against what is on
disk, exiting non-zero if they differ, without writing anything.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
IDENTITY_JSON = REPO_ROOT / "common" / "identity" / "identity.json"
HEADER_OUT = REPO_ROOT / "common" / "identity" / "include" / "reconclave" / "identity.h"
CSS_OUT = REPO_ROOT / "common" / "identity" / "identity.css"

GENERATED_BANNER = "GENERATED by tools/generate_identity.py from identity.json. Do not edit by hand."


def hex_to_rgb(value: str) -> tuple[int, int, int]:
    value = value.lstrip("#")
    return int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16)


def rgb_to_565(r: int, g: int, b: int) -> int:
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def cpp_ident(name: str) -> str:
    # accent -> kColorAccent, surface_raised -> kColorSurfaceRaised
    return "kColor" + "".join(part.capitalize() for part in name.split("_"))


def cpp_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def render_header(data: dict) -> str:
    brand = data["brand"]
    palette = data["palette"]
    lines: list[str] = []
    lines.append(f"// {GENERATED_BANNER}")
    lines.append("//")
    lines.append("// Canonical Reconclave brand identity for C++/embedded targets.")
    lines.append("// Palette tokens are provided both as 0xRRGGBB (uint32) and RGB565 (uint16).")
    lines.append("#ifndef RECONCLAVE_IDENTITY_H")
    lines.append("#define RECONCLAVE_IDENTITY_H")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace reconclave::identity {")
    lines.append("")
    lines.append("// Brand strings.")
    lines.append(f'inline constexpr char kBrandName[] = "{cpp_escape(brand["name"])}";')
    lines.append(f'inline constexpr char kTagline[] = "{cpp_escape(brand["tagline"])}";')
    lines.append(f'inline constexpr char kMascot[] = "{cpp_escape(brand["mascot"])}";')
    lines.append(f'inline constexpr char kUsbManufacturer[] = "{cpp_escape(brand["usb_manufacturer"])}";')
    lines.append("")
    lines.append("// Palette as 0xRRGGBB (LVGL/TFT full-colour use).")
    for name, spec in palette.items():
        r, g, b = hex_to_rgb(spec["hex"])
        packed = (r << 16) | (g << 8) | b
        lines.append(f"constexpr std::uint32_t {cpp_ident(name)} = 0x{packed:06x};  // {spec['role']}")
    lines.append("")
    lines.append("// Palette as RGB565 (16-bit panels, e.g. ST7735 via TFT_eSPI).")
    for name, spec in palette.items():
        r, g, b = hex_to_rgb(spec["hex"])
        lines.append(f"constexpr std::uint16_t {cpp_ident(name)}565 = 0x{rgb_to_565(r, g, b):04x};")
    lines.append("")
    lines.append("}  // namespace reconclave::identity")
    lines.append("")
    lines.append("#endif  // RECONCLAVE_IDENTITY_H")
    lines.append("")
    return "\n".join(lines)


def render_css(data: dict) -> str:
    palette = data["palette"]
    lines: list[str] = []
    lines.append(f"/* {GENERATED_BANNER} */")
    lines.append("/* Canonical Reconclave palette for web surfaces (desktop UI, device web UIs). */")
    lines.append("/* Each token is provided as a hex value and an -rgb triple; the triple lets a")
    lines.append("   consumer build translucent variants, e.g. rgba(var(--rc-accent-rgb), .14). */")
    lines.append(":root {")
    lines.append("  color-scheme: dark;")
    for name, spec in palette.items():
        css_name = name.replace("_", "-")
        r, g, b = hex_to_rgb(spec["hex"])
        lines.append(f"  --rc-{css_name}: {spec['hex']};  /* {spec['role']} */")
        lines.append(f"  --rc-{css_name}-rgb: {r},{g},{b};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale; write nothing.")
    args = parser.parse_args()

    data = json.loads(IDENTITY_JSON.read_text())
    outputs = {HEADER_OUT: render_header(data), CSS_OUT: render_css(data)}

    if args.check:
        stale = [p for p, content in outputs.items() if not p.exists() or p.read_text() != content]
        if stale:
            for p in stale:
                print(f"stale: {p.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("Run: python3 tools/generate_identity.py", file=sys.stderr)
            return 1
        print("identity headers up to date")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
